# docker-compose.yml
services:
  postgres:
    image: postgres:15
    container_name: postgres-1
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.9.3
    container_name: airflow-init-1
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: this-is-a-fixed-secret-key-keep-it-the-same
      AIRFLOW__CORE__FERNET_KEY: kJ1YrQK8zPj7yTmvZQqX1Isxsn9JK4OzE36suX5D5mA=
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
    command: >
      bash -lc 'set -euo pipefail;
      python -m pip install -r /requirements.txt;
      airflow db migrate;
      airflow users create --role Admin --username "${_AIRFLOW_WWW_USER_USERNAME:-admin}" --password "${_AIRFLOW_WWW_USER_PASSWORD:-admin}" --firstname A --lastname B --email admin@example.com;
      echo "== init complete =="'

  webserver:
    image: apache/airflow:2.9.3
    container_name: webserver-1
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__RBAC: "true"
      AIRFLOW__WEBSERVER__SECRET_KEY: this-is-a-fixed-secret-key-keep-it-the-same
      _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-snowflake==5.6.0 snowflake-connector-python==3.11.0 sentence-transformers==2.7.0 pinecone-client==5.0.1"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    command: ["bash","-lc","airflow webserver"]

  scheduler:
    image: apache/airflow:2.9.3
    container_name: scheduler-1
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: this-is-a-fixed-secret-key-keep-it-the-same
      _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-snowflake==5.6.0 snowflake-connector-python==3.11.0 sentence-transformers==2.7.0 pinecone-client==5.0.1"

    volumes:
      - ./dags:/opt/airflow/dags
    command: ["bash","-lc","airflow scheduler"]

volumes:
  pgdata:
